/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.glavne;
    
import forme.putnik.FormaPretragaPutnika;
import forme.putnik.FormaUnosPutnika;
import forme.putovanja.FormaPretragaPutovanja;
import forme.rezervacije.FormaPretragaRezervacija;
import forme.rezervacije.FormaUnosRezervacije;
import java.awt.event.WindowEvent;
import javax.swing.JLabel;
import kontroler.zaposleni.KontrolerZaposleni;
import osvezi.NitOsveziDatumIVreme;

/**
 *
 * @author Jovana
 */
public class FormaGlavna extends javax.swing.JFrame {
    /**
     * Creates new form FormaGlavna
     */
    public FormaGlavna() {
        initComponents();
        setLocationRelativeTo(null);
        
        KontrolerZaposleni.getInstance().ispisiZaposlenog(jLabelZaposleni);
        NitOsveziDatumIVreme osveziDatum = new NitOsveziDatumIVreme(this);
        osveziDatum.start();
    }

    public JLabel getjLabelZaposleni() {
        return jLabelZaposleni;
    }

    public JLabel getjLabelDatum() {
        return jLabelDatum;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelZaposleni = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelDatum = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jmbTuristickaAgencija = new javax.swing.JMenuBar();
        jmPutnici = new javax.swing.JMenu();
        jmiUnosPutnika = new javax.swing.JMenuItem();
        jmiPretragaPutnika = new javax.swing.JMenuItem();
        jmiIzmenaPutnika = new javax.swing.JMenuItem();
        jmiBrisanjePutnika = new javax.swing.JMenuItem();
        jmPutovanja = new javax.swing.JMenu();
        jmiPretragaPutovanja = new javax.swing.JMenuItem();
        jmRezervacije = new javax.swing.JMenu();
        jmiUnosRezervacije = new javax.swing.JMenuItem();
        jmiPretragaRezervacija = new javax.swing.JMenuItem();
        jmiIzmenaRezervacije = new javax.swing.JMenuItem();
        jmiBrisanjeRezervacije = new javax.swing.JMenuItem();
        jmZaposleni = new javax.swing.JMenu();
        jmiLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dobrodošli!");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelZaposleni.setText("Korisnik ");

        jLabelDatum.setText("Datum i vreme");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jmbTuristickaAgencija.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmPutnici.setText("Putnici");
        jmPutnici.setFocusable(false);
        jmPutnici.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiUnosPutnika.setText("Unos putnika");
        jmiUnosPutnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosPutnikaActionPerformed(evt);
            }
        });
        jmPutnici.add(jmiUnosPutnika);

        jmiPretragaPutnika.setText("Pretraga putnika");
        jmiPretragaPutnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaPutnikaActionPerformed(evt);
            }
        });
        jmPutnici.add(jmiPretragaPutnika);

        jmiIzmenaPutnika.setText("Izmena putnika");
        jmiIzmenaPutnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmenaPutnikaActionPerformed(evt);
            }
        });
        jmPutnici.add(jmiIzmenaPutnika);

        jmiBrisanjePutnika.setText("Brisanje putnika");
        jmiBrisanjePutnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBrisanjePutnikaActionPerformed(evt);
            }
        });
        jmPutnici.add(jmiBrisanjePutnika);

        jmbTuristickaAgencija.add(jmPutnici);

        jmPutovanja.setText("Putovanja");
        jmPutovanja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiPretragaPutovanja.setText("Pretraga putovanja");
        jmiPretragaPutovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaPutovanjaActionPerformed(evt);
            }
        });
        jmPutovanja.add(jmiPretragaPutovanja);

        jmbTuristickaAgencija.add(jmPutovanja);

        jmRezervacije.setText("Rezervacije");
        jmRezervacije.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiUnosRezervacije.setText("Unos rezervacije");
        jmiUnosRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosRezervacijeActionPerformed(evt);
            }
        });
        jmRezervacije.add(jmiUnosRezervacije);

        jmiPretragaRezervacija.setText("Pretraga rezervacija");
        jmiPretragaRezervacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaRezervacijaActionPerformed(evt);
            }
        });
        jmRezervacije.add(jmiPretragaRezervacija);

        jmiIzmenaRezervacije.setText("Izmena rezervacije");
        jmiIzmenaRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmenaRezervacijeActionPerformed(evt);
            }
        });
        jmRezervacije.add(jmiIzmenaRezervacije);

        jmiBrisanjeRezervacije.setText("Brisanje rezervacije");
        jmiBrisanjeRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBrisanjeRezervacijeActionPerformed(evt);
            }
        });
        jmRezervacije.add(jmiBrisanjeRezervacije);

        jmbTuristickaAgencija.add(jmRezervacije);

        jmZaposleni.setText("Korisnik");
        jmZaposleni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiLogout.setText("Logout");
        jmiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoutActionPerformed(evt);
            }
        });
        jmZaposleni.add(jmiLogout);

        jmbTuristickaAgencija.add(jmZaposleni);

        setJMenuBar(jmbTuristickaAgencija);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelZaposleni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDatum)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(jLabelDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabelZaposleni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosPutnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosPutnikaActionPerformed
        FormaUnosPutnika unosPutnika = new FormaUnosPutnika(this, false, null, "");
        //poslednja dva parametra su putnik i tip operacije
        unosPutnika.setVisible(true);
    }//GEN-LAST:event_jmiUnosPutnikaActionPerformed

    private void jmiPretragaPutnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaPutnikaActionPerformed
        FormaPretragaPutnika pretragaPutnika = new FormaPretragaPutnika(this, false, "view");
        //ovde je samo tip operacije jer ce tek forma pretraga imati izabranog putnika!!!
        pretragaPutnika.setVisible(true);
    }//GEN-LAST:event_jmiPretragaPutnikaActionPerformed

    private void jmiIzmenaPutnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmenaPutnikaActionPerformed
        FormaPretragaPutnika pretragaPutnika = new FormaPretragaPutnika(this, false, "update");
        pretragaPutnika.setVisible(true);
    }//GEN-LAST:event_jmiIzmenaPutnikaActionPerformed

    private void jmiBrisanjePutnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBrisanjePutnikaActionPerformed
        FormaPretragaPutnika pretragaPutnika = new FormaPretragaPutnika(this, false, "delete");
        pretragaPutnika.setVisible(true);
    }//GEN-LAST:event_jmiBrisanjePutnikaActionPerformed

    private void jmiUnosRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosRezervacijeActionPerformed
        FormaUnosRezervacije unosRez = new FormaUnosRezervacije(this, false, null, "");
        unosRez.setVisible(true);
    }//GEN-LAST:event_jmiUnosRezervacijeActionPerformed

    private void jmiPretragaRezervacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaRezervacijaActionPerformed
        FormaPretragaRezervacija pretragaRez = new FormaPretragaRezervacija(this, false, "view");
        pretragaRez.setVisible(true);
    }//GEN-LAST:event_jmiPretragaRezervacijaActionPerformed

    private void jmiIzmenaRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmenaRezervacijeActionPerformed
        FormaPretragaRezervacija pretragaRez = new FormaPretragaRezervacija(this, false, "update");
        pretragaRez.setVisible(true);
    }//GEN-LAST:event_jmiIzmenaRezervacijeActionPerformed

    private void jmiBrisanjeRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBrisanjeRezervacijeActionPerformed
        FormaPretragaRezervacija pretragaRez = new FormaPretragaRezervacija(this, false, "delete");
        pretragaRez.setVisible(true); 
    }//GEN-LAST:event_jmiBrisanjeRezervacijeActionPerformed

    private void jmiPretragaPutovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaPutovanjaActionPerformed
        FormaPretragaPutovanja pretragaPutovanja = new FormaPretragaPutovanja(this, false);
        pretragaPutovanja.setVisible(true);
    }//GEN-LAST:event_jmiPretragaPutovanjaActionPerformed

    private void jmiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoutActionPerformed
        formWindowClosing(new WindowEvent(this, 0));
        System.exit(0);
    }//GEN-LAST:event_jmiLogoutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        KontrolerZaposleni.getInstance().Logout();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JLabel jLabelZaposleni;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu jmPutnici;
    private javax.swing.JMenu jmPutovanja;
    private javax.swing.JMenu jmRezervacije;
    private javax.swing.JMenu jmZaposleni;
    private javax.swing.JMenuBar jmbTuristickaAgencija;
    private javax.swing.JMenuItem jmiBrisanjePutnika;
    private javax.swing.JMenuItem jmiBrisanjeRezervacije;
    private javax.swing.JMenuItem jmiIzmenaPutnika;
    private javax.swing.JMenuItem jmiIzmenaRezervacije;
    private javax.swing.JMenuItem jmiLogout;
    private javax.swing.JMenuItem jmiPretragaPutnika;
    private javax.swing.JMenuItem jmiPretragaPutovanja;
    private javax.swing.JMenuItem jmiPretragaRezervacija;
    private javax.swing.JMenuItem jmiUnosPutnika;
    private javax.swing.JMenuItem jmiUnosRezervacije;
    // End of variables declaration//GEN-END:variables
}
